name = "construction-os"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
NEXTAUTH_URL = "https://cacmn9.pages.dev"
NEXTAUTH_SECRET = "construction-os-secret-key-change-in-production"
